# Generated by Django 6.0.4 on 2026-04-22 20:28

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='DocumentGuide',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=150)),
                ('keywords', models.TextField(help_text='Comma separated keywords')),
                ('common_phrases', models.TextField(blank=True, help_text='User natural phrases for smart search', null=True)),
                ('required_documents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Guide',
                'verbose_name_plural': 'Document Guides',
                'db_table': 'DocumentGuide',
                'ordering': ['guide_id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('CNIC', models.CharField(max_length=15, unique=True, validators=[accounts.models.validate_cnic])),
                ('password', models.CharField(max_length=128)),
                ('DOB', models.DateField()),
                ('Mobile_number', models.CharField(max_length=15, validators=[accounts.models.validate_mobile])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=150)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='accounts.city')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'District',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=150)),
                ('google_address', models.TextField()),
                ('capacity', models.PositiveIntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('open_days', models.CharField(max_length=100)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='accounts.district')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
                'db_table': 'Office',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_wait_time', models.PositiveIntegerField(help_text='Minutes')),
                ('office', models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='accounts.office')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='accounts.users')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'Token',
                'ordering': ['-created_at'],
            },
        ),
    ]
