# Generated by Django 6.0.4 on 2026-05-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('people_count', models.PositiveIntegerField(help_text='Number of people detected by camera')),
                ('crowd_status', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('Crowded', 'Crowded')], default='Low', max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, related_name='crowd_snapshots', to='accounts.office')),
            ],
            options={
                'verbose_name': 'Crowd Snapshot',
                'verbose_name_plural': 'Crowd Snapshots',
                'db_table': 'CrowdSnapshot',
                'ordering': ['-captured_at'],
            },
        ),
    ]
